// Type definitions for @agntcy/slim-bindings-react-native
// This file exports the TypeScript type definitions generated by uniffi-bindgen-react-native

/**
 * Helper function to check if JSI bindings are available
 * @returns true if global.NativeSlimBindings is available, false otherwise
 */
export function isJSIBindingsAvailable(): boolean;

/**
 * Helper function to wait for JSI bindings to be available
 * @param timeoutMs Maximum time to wait in milliseconds (default: 5000)
 * @returns Promise that resolves when bindings are available or rejects on timeout
 */
export function waitForJSIBindings(timeoutMs?: number): Promise<void>;

// Re-export all the generated types
export * from '../generated/typescript/slim_bindings';

// For backward compatibility, also export as default
import * as SlimBindings from '../generated/typescript/slim_bindings';
export default SlimBindings;
