// Main entry point for @agntcy/slim-bindings-react-native
// This file exports the TypeScript bindings generated by uniffi-bindgen-react-native

// Import NativeModules to ensure native module is loaded
import { NativeModules } from 'react-native';

// Force the native module to load by accessing it
// This triggers the setBridge callback which installs JSI bindings
const { SlimBindings: NativeSlimBindingsModule } = NativeModules;

if (!NativeSlimBindingsModule) {
  console.warn('[SLIM] Native module SlimBindings not found in NativeModules');
} else {
  console.log('[SLIM] Native module SlimBindings loaded successfully');
  // Call install() to ensure JSI bindings are installed
  if (NativeSlimBindingsModule.install) {
    const result = NativeSlimBindingsModule.install();
    console.log('[SLIM] Native install() result:', result);
  }
}

/**
 * Helper function to check if JSI bindings are available
 * @returns true if global.NativeSlimBindings is available, false otherwise
 */
export function isJSIBindingsAvailable(): boolean {
  return typeof (global as any).NativeSlimBindings !== 'undefined';
}

/**
 * Helper function to wait for JSI bindings to be available
 * @param timeoutMs Maximum time to wait in milliseconds (default: 5000)
 * @returns Promise that resolves when bindings are available or rejects on timeout
 */
export function waitForJSIBindings(timeoutMs: number = 5000): Promise<void> {
  return new Promise((resolve, reject) => {
    if (isJSIBindingsAvailable()) {
      resolve();
      return;
    }

    const startTime = Date.now();
    const checkInterval = setInterval(() => {
      if (isJSIBindingsAvailable()) {
        clearInterval(checkInterval);
        console.log('[SLIM] JSI bindings became available');
        resolve();
      } else if (Date.now() - startTime > timeoutMs) {
        clearInterval(checkInterval);
        reject(new Error('Timeout waiting for JSI bindings to be available'));
      }
    }, 50);
  });
}

// Re-export all the generated bindings
export * from '../generated/typescript/slim_bindings';

// For backward compatibility, also export as default
import * as SlimBindings from '../generated/typescript/slim_bindings';
export default SlimBindings;
