// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: example.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExampleString  string                 `protobuf:"bytes,1,opt,name=example_string,json=exampleString,proto3" json:"example_string,omitempty"`
	ExampleInteger int64                  `protobuf:"varint,2,opt,name=example_integer,json=exampleInteger,proto3" json:"example_integer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExampleRequest) Reset() {
	*x = ExampleRequest{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRequest) ProtoMessage() {}

func (x *ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRequest.ProtoReflect.Descriptor instead.
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleRequest) GetExampleString() string {
	if x != nil {
		return x.ExampleString
	}
	return ""
}

func (x *ExampleRequest) GetExampleInteger() int64 {
	if x != nil {
		return x.ExampleInteger
	}
	return 0
}

type ExampleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExampleString  string                 `protobuf:"bytes,1,opt,name=example_string,json=exampleString,proto3" json:"example_string,omitempty"`
	ExampleInteger int64                  `protobuf:"varint,2,opt,name=example_integer,json=exampleInteger,proto3" json:"example_integer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleResponse) GetExampleString() string {
	if x != nil {
		return x.ExampleString
	}
	return ""
}

func (x *ExampleResponse) GetExampleInteger() int64 {
	if x != nil {
		return x.ExampleInteger
	}
	return 0
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\x0fexample_service\"`\n" +
	"\x0eExampleRequest\x12%\n" +
	"\x0eexample_string\x18\x01 \x01(\tR\rexampleString\x12'\n" +
	"\x0fexample_integer\x18\x02 \x01(\x03R\x0eexampleInteger\"a\n" +
	"\x0fExampleResponse\x12%\n" +
	"\x0eexample_string\x18\x01 \x01(\tR\rexampleString\x12'\n" +
	"\x0fexample_integer\x18\x02 \x01(\x03R\x0eexampleInteger2\xd0\x03\n" +
	"\x04Test\x12V\n" +
	"\x11ExampleUnaryUnary\x12\x1f.example_service.ExampleRequest\x1a .example_service.ExampleResponse\x12Y\n" +
	"\x12ExampleUnaryStream\x12\x1f.example_service.ExampleRequest\x1a .example_service.ExampleResponse0\x01\x12\\\n" +
	"\x15ExampleUnaryStreamTwo\x12\x1f.example_service.ExampleRequest\x1a .example_service.ExampleResponse0\x01\x12Y\n" +
	"\x12ExampleStreamUnary\x12\x1f.example_service.ExampleRequest\x1a .example_service.ExampleResponse(\x01\x12\\\n" +
	"\x13ExampleStreamStream\x12\x1f.example_service.ExampleRequest\x1a .example_service.ExampleResponse(\x010\x01B\xbd\x01\n" +
	"\x13com.example_serviceB\fExampleProtoP\x01Z@github.com/agntcy/slim-bindings/go/examples/slimrpc/simple/types\xa2\x02\x03EXX\xaa\x02\x0eExampleService\xca\x02\x0eExampleService\xe2\x02\x1aExampleService\\GPBMetadata\xea\x02\x0eExampleServiceb\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_proto_goTypes = []any{
	(*ExampleRequest)(nil),  // 0: example_service.ExampleRequest
	(*ExampleResponse)(nil), // 1: example_service.ExampleResponse
}
var file_example_proto_depIdxs = []int32{
	0, // 0: example_service.Test.ExampleUnaryUnary:input_type -> example_service.ExampleRequest
	0, // 1: example_service.Test.ExampleUnaryStream:input_type -> example_service.ExampleRequest
	0, // 2: example_service.Test.ExampleUnaryStreamTwo:input_type -> example_service.ExampleRequest
	0, // 3: example_service.Test.ExampleStreamUnary:input_type -> example_service.ExampleRequest
	0, // 4: example_service.Test.ExampleStreamStream:input_type -> example_service.ExampleRequest
	1, // 5: example_service.Test.ExampleUnaryUnary:output_type -> example_service.ExampleResponse
	1, // 6: example_service.Test.ExampleUnaryStream:output_type -> example_service.ExampleResponse
	1, // 7: example_service.Test.ExampleUnaryStreamTwo:output_type -> example_service.ExampleResponse
	1, // 8: example_service.Test.ExampleStreamUnary:output_type -> example_service.ExampleResponse
	1, // 9: example_service.Test.ExampleStreamStream:output_type -> example_service.ExampleResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
