crates:
  - name: agntcy-slim-bindings-ffi
    path: ../rust

web:
  manifestPath: wasm/Cargo.toml
  manifestPatchFile: wasm.Cargo.patch.toml
  wasmCrateName: slim-bindings-react-native
  features:
    - web
  defaultFeatures: false
  workspace: false
  target: web
  entrypoint: src/index.web.ts
  tsBindings: generated/web
