# Generated by protoc-slimrpc-plugin
# This file is generated from an embedded template. Do not edit directly.

from datetime import timedelta
from typing import Optional

from google.rpc import code_pb2 as code__pb2

import slim_bindings

from . import example_pb2 as pb2


class TestStub:
    """Client stub for Test."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A slim_bindings.Channel.
        """
        self._channel = channel

    async def ExampleUnaryUnary(self, request: pb2.ExampleRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> pb2.ExampleResponse:
        """Call ExampleUnaryUnary method."""
        response_bytes = await self._channel.call_unary_async(
            "example_service.Test",
            "ExampleUnaryUnary",
            pb2.ExampleRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return pb2.ExampleResponse.FromString(response_bytes)

    async def ExampleUnaryStream(self, request: pb2.ExampleRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Call ExampleUnaryStream method."""
        response_stream = await self._channel.call_unary_stream_async(
            "example_service.Test",
            "ExampleUnaryStream",
            pb2.ExampleRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        while True:
            stream_msg = await response_stream.next_async()
            if stream_msg.is_end():
                break
            if stream_msg.is_error():
                raise stream_msg[0]
            if stream_msg.is_data():
                yield pb2.ExampleResponse.FromString(stream_msg[0])

    async def ExampleStreamUnary(self, request_iterator, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> pb2.ExampleResponse:
        """Call ExampleStreamUnary method."""
        request_stream = self._channel.call_stream_unary(
            "example_service.Test",
            "ExampleStreamUnary",
            timeout,
            metadata,
        )
        async for request in request_iterator:
            await request_stream.send_async(pb2.ExampleRequest.SerializeToString(request))
        response_bytes = await request_stream.finalize_stream_async()
        return pb2.ExampleResponse.FromString(response_bytes)

    async def ExampleStreamStream(self, request_iterator, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Call ExampleStreamStream method."""
        bidi_stream = self._channel.call_stream_stream(
            "example_service.Test",
            "ExampleStreamStream",
            timeout,
            metadata,
        )

        async def send_requests():
            async for request in request_iterator:
                await bidi_stream.send_async(pb2.ExampleRequest.SerializeToString(request))
            await bidi_stream.close_send_async()

        async def receive_responses():
            while True:
                stream_msg = await bidi_stream.recv_async()
                if stream_msg.is_end():
                    break
                if stream_msg.is_error():
                    raise stream_msg[0]
                if stream_msg.is_data():
                    yield pb2.ExampleResponse.FromString(stream_msg[0])

        # Start sending in background
        import asyncio
        send_task = asyncio.create_task(send_requests())

        try:
            async for response in receive_responses():
                yield response
        finally:
            await send_task



class TestGroupStub:
    """Multicast (group) client stub for Test.

    Requires a channel created with ``Channel.new_group*`` targeting multiple
    server instances. All methods are async generators that yield
    ``(source, response)`` tuples — one pair per incoming message.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A slim_bindings.Channel created with Channel.new_group*.
        """
        self._channel = channel

    async def ExampleUnaryUnary(self, request: pb2.ExampleRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Multicast ExampleUnaryUnary: one response per server."""
        reader = await self._channel.call_multicast_unary_async(
            "example_service.Test",
            "ExampleUnaryUnary",
            pb2.ExampleRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        while True:
            msg = await reader.next_async()
            if msg.is_end():
                break
            if msg.is_error():
                raise msg.error
            if msg.is_data():
                yield msg.item.context, pb2.ExampleResponse.FromString(msg.item.message)

    async def ExampleUnaryStream(self, request: pb2.ExampleRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Multicast ExampleUnaryStream: streaming responses per server."""
        reader = await self._channel.call_multicast_unary_stream_async(
            "example_service.Test",
            "ExampleUnaryStream",
            pb2.ExampleRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        while True:
            msg = await reader.next_async()
            if msg.is_end():
                break
            if msg.is_error():
                raise msg.error
            if msg.is_data():
                yield msg.item.context, pb2.ExampleResponse.FromString(msg.item.message)

    async def ExampleStreamUnary(self, request_iterator, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Multicast ExampleStreamUnary: one response per server after streaming requests."""
        handler = self._channel.call_multicast_stream_unary(
            "example_service.Test",
            "ExampleStreamUnary",
            timeout,
            metadata,
        )
        async for request in request_iterator:
            await handler.send_async(pb2.ExampleRequest.SerializeToString(request))
        await handler.close_send_async()
        while True:
            msg = await handler.recv_async()
            if msg.is_end():
                break
            if msg.is_error():
                raise msg.error
            if msg.is_data():
                yield msg.item.context, pb2.ExampleResponse.FromString(msg.item.message)

    async def ExampleStreamStream(self, request_iterator, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Multicast ExampleStreamStream: streaming requests and responses."""
        handler = self._channel.call_multicast_stream_stream(
            "example_service.Test",
            "ExampleStreamStream",
            timeout,
            metadata,
        )

        async def send_requests():
            async for request in request_iterator:
                await handler.send_async(pb2.ExampleRequest.SerializeToString(request))
            await handler.close_send_async()

        import asyncio
        send_task = asyncio.create_task(send_requests())

        try:
            while True:
                msg = await handler.recv_async()
                if msg.is_end():
                    break
                if msg.is_error():
                    raise msg.error
                if msg.is_data():
                    yield msg.item.context, pb2.ExampleResponse.FromString(msg.item.message)
        finally:
            await send_task



class TestServicer:
    """Server servicer for Test. Implement this class to provide your service logic."""

    def ExampleUnaryUnary(self, request, context):
        """Method for ExampleUnaryUnary. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def ExampleUnaryStream(self, request, context):
        """Method for ExampleUnaryStream. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def ExampleStreamUnary(self, request_iterator, context):
        """Method for ExampleStreamUnary. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def ExampleStreamStream(self, request_iterator, context):
        """Method for ExampleStreamStream. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )




class _TestServicer_ExampleUnaryUnary_Handler(slim_bindings.UnaryUnaryHandler):
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = pb2.ExampleRequest.FromString(request)
            response = await self.servicer.ExampleUnaryUnary(request_msg, context)
            return pb2.ExampleResponse.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _TestServicer_ExampleUnaryStream_Handler(slim_bindings.UnaryStreamHandler):
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context, sink: slim_bindings.ResponseSink):
        try:
            request_msg = pb2.ExampleRequest.FromString(request)
            response_iter = self.servicer.ExampleUnaryStream(request_msg, context)
            async for response in response_iter:
                await sink.send_async(pb2.ExampleResponse.SerializeToString(response))
            await sink.close_async()
        except slim_bindings.RpcError as e:
            await sink.send_error_async(e)
        except Exception as e:
            rpc_error = slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )
            await sink.send_error_async(rpc_error)

class _TestServicer_ExampleStreamUnary_Handler(slim_bindings.StreamUnaryHandler):
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, stream: slim_bindings.RequestStream, context: slim_bindings.Context) -> bytes:
        try:
            async def request_iterator():
                while True:
                    stream_msg = await stream.next_async()
                    if stream_msg.is_end():
                        break
                    if stream_msg.is_error():
                        raise stream_msg[0]
                    if stream_msg.is_data():
                        yield pb2.ExampleRequest.FromString(stream_msg[0])

            response = await self.servicer.ExampleStreamUnary(request_iterator(), context)
            return pb2.ExampleResponse.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _TestServicer_ExampleStreamStream_Handler(slim_bindings.StreamStreamHandler):
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, stream: slim_bindings.RequestStream, context: slim_bindings.Context, sink: slim_bindings.ResponseSink):
        try:
            async def request_iterator():
                while True:
                    stream_msg = await stream.next_async()
                    if stream_msg.is_end():
                        break
                    if stream_msg.is_error():
                        raise stream_msg[0]
                    if stream_msg.is_data():
                        yield pb2.ExampleRequest.FromString(stream_msg[0])

            response_iter = self.servicer.ExampleStreamStream(request_iterator(), context)
            async for response in response_iter:
                await sink.send_async(pb2.ExampleResponse.SerializeToString(response))
            await sink.close_async()
        except slim_bindings.RpcError as e:
            await sink.send_error_async(e)
        except Exception as e:
            rpc_error = slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )
            await sink.send_error_async(rpc_error)


def add_TestServicer_to_server(servicer, server: slim_bindings.Server):
    server.register_unary_unary(
        service_name="example_service.Test",
        method_name="ExampleUnaryUnary",
        handler=_TestServicer_ExampleUnaryUnary_Handler(servicer),
    )
    server.register_unary_stream(
        service_name="example_service.Test",
        method_name="ExampleUnaryStream",
        handler=_TestServicer_ExampleUnaryStream_Handler(servicer),
    )
    server.register_stream_unary(
        service_name="example_service.Test",
        method_name="ExampleStreamUnary",
        handler=_TestServicer_ExampleStreamUnary_Handler(servicer),
    )
    server.register_stream_stream(
        service_name="example_service.Test",
        method_name="ExampleStreamStream",
        handler=_TestServicer_ExampleStreamStream_Handler(servicer),
    )
