// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example_service;

@kotlin.jvm.JvmName("-initializeexampleRequest")
public inline fun exampleRequest(block: com.example_service.ExampleRequestKt.Dsl.() -> kotlin.Unit): com.example_service.ExampleRequest =
  com.example_service.ExampleRequestKt.Dsl._create(com.example_service.ExampleRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `example_service.ExampleRequest`
 */
public object ExampleRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example_service.ExampleRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example_service.ExampleRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example_service.ExampleRequest = _builder.build()

    /**
     * `string example_string = 1 [json_name = "exampleString"];`
     */
    public var exampleString: kotlin.String
      @kotlin.jvm.JvmName("getExampleString")
        get() = _builder.exampleString
      @kotlin.jvm.JvmName("setExampleString")
        set(value) {
        _builder.exampleString = value
      }
    /**
     * `string example_string = 1 [json_name = "exampleString"];`
     */
    public fun clearExampleString() {
      _builder.clearExampleString()
    }

    /**
     * `int64 example_integer = 2 [json_name = "exampleInteger"];`
     */
    public var exampleInteger: kotlin.Long
      @kotlin.jvm.JvmName("getExampleInteger")
        get() = _builder.exampleInteger
      @kotlin.jvm.JvmName("setExampleInteger")
        set(value) {
        _builder.exampleInteger = value
      }
    /**
     * `int64 example_integer = 2 [json_name = "exampleInteger"];`
     */
    public fun clearExampleInteger() {
      _builder.clearExampleInteger()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example_service.ExampleRequest.copy(block: `com.example_service`.ExampleRequestKt.Dsl.() -> kotlin.Unit): com.example_service.ExampleRequest =
  `com.example_service`.ExampleRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

