// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example.proto
// Protobuf Java Version: 4.29.3

package com.example_service;

public final class ExampleProto {
  private ExampleProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ExampleProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_service_ExampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_service_ExampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_service_ExampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_service_ExampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\017example_service\"`\n\016Exam" +
      "pleRequest\022%\n\016example_string\030\001 \001(\tR\rexam" +
      "pleString\022\'\n\017example_integer\030\002 \001(\003R\016exam" +
      "pleInteger\"a\n\017ExampleResponse\022%\n\016example" +
      "_string\030\001 \001(\tR\rexampleString\022\'\n\017example_" +
      "integer\030\002 \001(\003R\016exampleInteger2\362\002\n\004Test\022V" +
      "\n\021ExampleUnaryUnary\022\037.example_service.Ex" +
      "ampleRequest\032 .example_service.ExampleRe" +
      "sponse\022Y\n\022ExampleUnaryStream\022\037.example_s" +
      "ervice.ExampleRequest\032 .example_service." +
      "ExampleResponse0\001\022Y\n\022ExampleStreamUnary\022" +
      "\037.example_service.ExampleRequest\032 .examp" +
      "le_service.ExampleResponse(\001\022\\\n\023ExampleS" +
      "treamStream\022\037.example_service.ExampleReq" +
      "uest\032 .example_service.ExampleResponse(\001" +
      "0\001B{\n\023com.example_serviceB\014ExampleProtoP" +
      "\001\242\002\003EXX\252\002\016ExampleService\312\002\016ExampleServic" +
      "e\342\002\032ExampleService\\GPBMetadata\352\002\016Example" +
      "Serviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_service_ExampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_service_ExampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_service_ExampleRequest_descriptor,
        new java.lang.String[] { "ExampleString", "ExampleInteger", });
    internal_static_example_service_ExampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_service_ExampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_service_ExampleResponse_descriptor,
        new java.lang.String[] { "ExampleString", "ExampleInteger", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
