// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

use anyhow::{Context, Result};
use heck::ToUpperCamelCase;
use prost_types::compiler::{
    CodeGeneratorRequest, CodeGeneratorResponse, code_generator_response::File,
};
use prost_types::{DescriptorProto, FileDescriptorProto};
use std::collections::HashMap;

const FILE_TEMPLATE: &str = r#"// Code generated by protoc-gen-slimrpc-kotlin. DO NOT EDIT.
// source: {{PROTO_FILE}}

{{PACKAGE_DECL}}

import io.agntcy.slim.bindings.BidiStreamHandler
import io.agntcy.slim.bindings.Channel
import io.agntcy.slim.bindings.Context
import io.agntcy.slim.bindings.RequestStream
import io.agntcy.slim.bindings.RequestStreamWriter
import io.agntcy.slim.bindings.ResponseSink
import io.agntcy.slim.bindings.ResponseStreamReader
import io.agntcy.slim.bindings.RpcCode
import io.agntcy.slim.bindings.RpcException
import io.agntcy.slim.bindings.Server
import io.agntcy.slim.bindings.UnaryStreamHandler
import io.agntcy.slim.bindings.UnaryUnaryHandler
import io.agntcy.slim.bindings.StreamUnaryHandler
import io.agntcy.slim.bindings.StreamStreamHandler
import io.agntcy.slim.bindings.slimrpc.ClientRequestStream
import io.agntcy.slim.bindings.slimrpc.ClientBidiStream
import io.agntcy.slim.bindings.MulticastResponseReader
import io.agntcy.slim.bindings.MulticastBidiStreamHandler
import io.agntcy.slim.bindings.slimrpc.MulticastResponseStream
import io.agntcy.slim.bindings.slimrpc.MulticastClientBidiStream
import io.agntcy.slim.bindings.slimrpc.parse
import io.agntcy.slim.bindings.slimrpc.toRpcException
import java.time.Duration

{{SERVICE_DEFINITION}}
"#;

const SERVICE_TEMPLATE: &str = r#"object {{SERVICE_NAME}}Slimrpc {
    const val SERVICE_NAME = "{{FULL_SERVICE_NAME}}"

    interface {{SERVICE_NAME}}Client {
{{CLIENT_METHODS}}
    }

    class {{SERVICE_NAME}}ClientImpl(private val channel: Channel) : {{SERVICE_NAME}}Client {
{{CLIENT_METHOD_IMPLS}}
    }

    interface {{SERVICE_NAME}}Server {
{{SERVER_METHODS}}
    }

    open class Unimplemented{{SERVICE_NAME}}Server : {{SERVICE_NAME}}Server {
{{UNIMPLEMENTED_METHODS}}
    }

    fun register{{SERVICE_NAME}}Server(server: Server, impl: {{SERVICE_NAME}}Server) {
{{REGISTER_METHODS}}
    }

{{HANDLER_IMPLS}}
    interface {{SERVICE_NAME}}GroupClient {
{{GROUP_CLIENT_METHODS}}
    }

    class {{SERVICE_NAME}}GroupClientImpl(private val channel: Channel) : {{SERVICE_NAME}}GroupClient {
{{GROUP_CLIENT_METHOD_IMPLS}}
    }
}
"#;

const CLIENT_UNARY_UNARY_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): {{OUTPUT_TYPE}}
"#;

const CLIENT_UNARY_STREAM_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): ResponseStreamReader
"#;

const CLIENT_STREAM_UNARY_METHOD: &str = r#"        fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): ClientRequestStream<{{INPUT_TYPE}}, {{OUTPUT_TYPE}}>
"#;

const CLIENT_STREAM_STREAM_METHOD: &str = r#"        fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): ClientBidiStream<{{INPUT_TYPE}}>
"#;

const CLIENT_UNARY_UNARY_IMPL: &str = r#"        override suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): {{OUTPUT_TYPE}} {
            val bytes = channel.callUnaryAsync(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                request.toByteArray(),
                timeout,
                metadata
            )
            return parse(bytes, {{OUTPUT_TYPE}}.parser())
        }

"#;

const CLIENT_UNARY_STREAM_IMPL: &str = r#"        override suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): ResponseStreamReader {
            return channel.callUnaryStreamAsync(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                request.toByteArray(),
                timeout,
                metadata
            )
        }

"#;

const CLIENT_STREAM_UNARY_IMPL: &str = r#"        override fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): ClientRequestStream<{{INPUT_TYPE}}, {{OUTPUT_TYPE}}> {
            val writer = channel.callStreamUnary(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                timeout,
                metadata
            )
            return ClientRequestStream(writer, { it.toByteArray() }, { bytes -> parse(bytes, {{OUTPUT_TYPE}}.parser()) })
        }

"#;

const CLIENT_STREAM_STREAM_IMPL: &str = r#"        override fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): ClientBidiStream<{{INPUT_TYPE}}> {
            val handler = channel.callStreamStream(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                timeout,
                metadata
            )
            return ClientBidiStream(handler) { it.toByteArray() }
        }

"#;

const SERVER_UNARY_UNARY_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, context: Context): {{OUTPUT_TYPE}}
"#;

const SERVER_UNARY_STREAM_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, context: Context, sink: ResponseSink)
"#;

const SERVER_STREAM_UNARY_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(stream: RequestStream, context: Context): {{OUTPUT_TYPE}}
"#;

const SERVER_STREAM_STREAM_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(stream: RequestStream, context: Context, sink: ResponseSink)
"#;

const UNIMPLEMENTED_UNARY_UNARY: &str = r#"        override suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, context: Context): {{OUTPUT_TYPE}} {
            throw UnsupportedOperationException("Method {{METHOD_NAME}} not implemented")
        }

"#;

const UNIMPLEMENTED_UNARY_STREAM: &str = r#"        override suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, context: Context, sink: ResponseSink) {
            throw UnsupportedOperationException("Method {{METHOD_NAME}} not implemented")
        }

"#;

const UNIMPLEMENTED_STREAM_UNARY: &str = r#"        override suspend fun {{METHOD_NAME}}(stream: RequestStream, context: Context): {{OUTPUT_TYPE}} {
            throw UnsupportedOperationException("Method {{METHOD_NAME}} not implemented")
        }

"#;

const UNIMPLEMENTED_STREAM_STREAM: &str = r#"        override suspend fun {{METHOD_NAME}}(stream: RequestStream, context: Context, sink: ResponseSink) {
            throw UnsupportedOperationException("Method {{METHOD_NAME}} not implemented")
        }

"#;

const REGISTER_UNARY_UNARY: &str = r#"        server.registerUnaryUnary(SERVICE_NAME, "{{METHOD_NAME}}", {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(impl))
"#;

const REGISTER_UNARY_STREAM: &str = r#"        server.registerUnaryStream(SERVICE_NAME, "{{METHOD_NAME}}", {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(impl))
"#;

const REGISTER_STREAM_UNARY: &str = r#"        server.registerStreamUnary(SERVICE_NAME, "{{METHOD_NAME}}", {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(impl))
"#;

const REGISTER_STREAM_STREAM: &str = r#"        server.registerStreamStream(SERVICE_NAME, "{{METHOD_NAME}}", {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(impl))
"#;

const HANDLER_UNARY_UNARY: &str = r#"    private class {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(private val impl: {{SERVICE_NAME}}Server) : UnaryUnaryHandler {
        override suspend fun handle(request: ByteArray, context: Context): ByteArray {
            val parsed = parse(request, {{INPUT_TYPE}}.parser())
            return impl.{{METHOD_NAME}}(parsed, context).toByteArray()
        }
    }

"#;

const HANDLER_UNARY_STREAM: &str = r#"    private class {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(private val impl: {{SERVICE_NAME}}Server) : UnaryStreamHandler {
        override suspend fun handle(request: ByteArray, context: Context, sink: ResponseSink) {
            val parsed = try {
                parse(request, {{INPUT_TYPE}}.parser())
            } catch (e: Exception) {
                val rpcErr = RpcException.Rpc(RpcCode.INVALID_ARGUMENT, e.message ?: "invalid request", null)
                try { sink.sendErrorAsync(rpcErr) } catch (_: Exception) {}
                throw rpcErr
            }
            try {
                impl.{{METHOD_NAME}}(parsed, context, sink)
                sink.closeAsync()
            } catch (e: Exception) {
                val rpcErr = toRpcException(e, RpcCode.INTERNAL)
                try { sink.sendErrorAsync(rpcErr) } catch (_: Exception) {}
                throw rpcErr
            }
        }
    }

"#;

const HANDLER_STREAM_UNARY: &str = r#"    private class {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(private val impl: {{SERVICE_NAME}}Server) : StreamUnaryHandler {
        override suspend fun handle(stream: RequestStream, context: Context): ByteArray {
            try {
                return impl.{{METHOD_NAME}}(stream, context).toByteArray()
            } catch (e: Exception) {
                throw toRpcException(e, RpcCode.INTERNAL)
            }
        }
    }

"#;

const HANDLER_STREAM_STREAM: &str = r#"    private class {{SERVICE_NAME}}_{{METHOD_NAME}}_Handler(private val impl: {{SERVICE_NAME}}Server) : StreamStreamHandler {
        override suspend fun handle(stream: RequestStream, context: Context, sink: ResponseSink) {
            try {
                impl.{{METHOD_NAME}}(stream, context, sink)
                sink.closeAsync()
            } catch (e: Exception) {
                val rpcErr = toRpcException(e, RpcCode.INTERNAL)
                try { sink.sendErrorAsync(rpcErr) } catch (_: Exception) {}
                throw rpcErr
            }
        }
    }

"#;

const GROUP_CLIENT_UNARY_UNARY_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<{{OUTPUT_TYPE}}>
"#;

const GROUP_CLIENT_UNARY_UNARY_IMPL: &str = r#"        override suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<{{OUTPUT_TYPE}}> {
            val reader = channel.callMulticastUnaryAsync(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                request.toByteArray(),
                timeout,
                metadata
            )
            return MulticastResponseStream(reader) { bytes -> parse(bytes, {{OUTPUT_TYPE}}.parser()) }
        }

"#;

const GROUP_CLIENT_UNARY_STREAM_METHOD: &str = r#"        suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<{{OUTPUT_TYPE}}>
"#;

const GROUP_CLIENT_UNARY_STREAM_IMPL: &str = r#"        override suspend fun {{METHOD_NAME}}(request: {{INPUT_TYPE}}, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<{{OUTPUT_TYPE}}> {
            val reader = channel.callMulticastUnaryStreamAsync(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                request.toByteArray(),
                timeout,
                metadata
            )
            return MulticastResponseStream(reader) { bytes -> parse(bytes, {{OUTPUT_TYPE}}.parser()) }
        }

"#;

const GROUP_CLIENT_STREAM_UNARY_METHOD: &str = r#"        fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<{{INPUT_TYPE}}, {{OUTPUT_TYPE}}>
"#;

const GROUP_CLIENT_STREAM_UNARY_IMPL: &str = r#"        override fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<{{INPUT_TYPE}}, {{OUTPUT_TYPE}}> {
            val handler = channel.callMulticastStreamUnary(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                timeout,
                metadata
            )
            return MulticastClientBidiStream(handler, { it.toByteArray() }, { bytes -> parse(bytes, {{OUTPUT_TYPE}}.parser()) })
        }

"#;

const GROUP_CLIENT_STREAM_STREAM_METHOD: &str = r#"        fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<{{INPUT_TYPE}}, {{OUTPUT_TYPE}}>
"#;

const GROUP_CLIENT_STREAM_STREAM_IMPL: &str = r#"        override fun {{METHOD_NAME}}(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<{{INPUT_TYPE}}, {{OUTPUT_TYPE}}> {
            val handler = channel.callMulticastStreamStream(
                SERVICE_NAME,
                "{{METHOD_NAME}}",
                timeout,
                metadata
            )
            return MulticastClientBidiStream(handler, { it.toByteArray() }, { bytes -> parse(bytes, {{OUTPUT_TYPE}}.parser()) })
        }

"#;

struct RpcTemplates {
    client_method: &'static str,
    client_impl: &'static str,
    server_method: &'static str,
    unimplemented: &'static str,
    register: &'static str,
    handler: &'static str,
    group_client_method: &'static str,
    group_client_impl: &'static str,
}

const UNARY_UNARY_TEMPLATES: RpcTemplates = RpcTemplates {
    client_method: CLIENT_UNARY_UNARY_METHOD,
    client_impl: CLIENT_UNARY_UNARY_IMPL,
    server_method: SERVER_UNARY_UNARY_METHOD,
    unimplemented: UNIMPLEMENTED_UNARY_UNARY,
    register: REGISTER_UNARY_UNARY,
    handler: HANDLER_UNARY_UNARY,
    group_client_method: GROUP_CLIENT_UNARY_UNARY_METHOD,
    group_client_impl: GROUP_CLIENT_UNARY_UNARY_IMPL,
};

const UNARY_STREAM_TEMPLATES: RpcTemplates = RpcTemplates {
    client_method: CLIENT_UNARY_STREAM_METHOD,
    client_impl: CLIENT_UNARY_STREAM_IMPL,
    server_method: SERVER_UNARY_STREAM_METHOD,
    unimplemented: UNIMPLEMENTED_UNARY_STREAM,
    register: REGISTER_UNARY_STREAM,
    handler: HANDLER_UNARY_STREAM,
    group_client_method: GROUP_CLIENT_UNARY_STREAM_METHOD,
    group_client_impl: GROUP_CLIENT_UNARY_STREAM_IMPL,
};

const STREAM_UNARY_TEMPLATES: RpcTemplates = RpcTemplates {
    client_method: CLIENT_STREAM_UNARY_METHOD,
    client_impl: CLIENT_STREAM_UNARY_IMPL,
    server_method: SERVER_STREAM_UNARY_METHOD,
    unimplemented: UNIMPLEMENTED_STREAM_UNARY,
    register: REGISTER_STREAM_UNARY,
    handler: HANDLER_STREAM_UNARY,
    group_client_method: GROUP_CLIENT_STREAM_UNARY_METHOD,
    group_client_impl: GROUP_CLIENT_STREAM_UNARY_IMPL,
};

const STREAM_STREAM_TEMPLATES: RpcTemplates = RpcTemplates {
    client_method: CLIENT_STREAM_STREAM_METHOD,
    client_impl: CLIENT_STREAM_STREAM_IMPL,
    server_method: SERVER_STREAM_STREAM_METHOD,
    unimplemented: UNIMPLEMENTED_STREAM_STREAM,
    register: REGISTER_STREAM_STREAM,
    handler: HANDLER_STREAM_STREAM,
    group_client_method: GROUP_CLIENT_STREAM_STREAM_METHOD,
    group_client_impl: GROUP_CLIENT_STREAM_STREAM_IMPL,
};

fn rpc_templates(client_streaming: bool, server_streaming: bool) -> &'static RpcTemplates {
    match (client_streaming, server_streaming) {
        (false, false) => &UNARY_UNARY_TEMPLATES,
        (false, true) => &UNARY_STREAM_TEMPLATES,
        (true, false) => &STREAM_UNARY_TEMPLATES,
        (true, true) => &STREAM_STREAM_TEMPLATES,
    }
}

fn apply(template: &str, vars: &[(&str, &str)]) -> String {
    let mut result = template.to_string();
    for (key, value) in vars {
        result = result.replace(key, value);
    }
    result
}

#[derive(Clone)]
struct KotlinFileInfo {
    java_package: String,
    outer_class: String,
    multiple_files: bool,
}

fn file_name_base(file_name: &str) -> String {
    file_name
        .split('/')
        .next_back()
        .unwrap_or(file_name)
        .strip_suffix(".proto")
        .unwrap_or(file_name)
        .to_string()
}

fn kotlin_file_info(file: &FileDescriptorProto) -> KotlinFileInfo {
    let java_package = file
        .options
        .as_ref()
        .and_then(|opts| opts.java_package.clone())
        .filter(|s: &String| !s.is_empty())
        .or_else(|| file.package.clone())
        .unwrap_or_default();

    let base_name = file
        .name
        .as_deref()
        .map(file_name_base)
        .unwrap_or_else(|| "unknown_proto".to_string());

    let outer_class = file
        .options
        .as_ref()
        .and_then(|opts| opts.java_outer_classname.clone())
        .filter(|s: &String| !s.is_empty())
        .unwrap_or_else(|| format!("{}Proto", base_name.to_upper_camel_case()));

    let multiple_files = file
        .options
        .as_ref()
        .and_then(|opts| opts.java_multiple_files)
        .unwrap_or(false);

    KotlinFileInfo {
        java_package,
        outer_class,
        multiple_files,
    }
}

fn collect_message_types(
    proto_prefix: String,
    kotlin_prefix: String,
    messages: &[DescriptorProto],
    type_map: &mut HashMap<String, String>,
) {
    for msg in messages {
        let Some(name) = msg.name.as_ref() else {
            continue;
        };

        let proto_full = if proto_prefix.is_empty() {
            format!(".{}", name)
        } else {
            format!(".{}.{}", proto_prefix, name)
        };

        let kotlin_full = if kotlin_prefix.is_empty() {
            name.to_string()
        } else {
            format!("{}.{}", kotlin_prefix, name)
        };

        type_map.insert(proto_full.clone(), kotlin_full.clone());

        let nested_proto_prefix = if proto_prefix.is_empty() {
            name.to_string()
        } else {
            format!("{}.{}", proto_prefix, name)
        };

        collect_message_types(nested_proto_prefix, kotlin_full, &msg.nested_type, type_map);
    }
}

fn resolve_kotlin_type(
    full_type_name: &str,
    current_package: &str,
    type_map: &HashMap<String, String>,
) -> String {
    let trimmed = full_type_name.trim_start_matches('.');

    if trimmed.starts_with("google.protobuf.") {
        let type_name = trimmed.rsplit('.').next().unwrap_or(trimmed);
        return format!("com.google.protobuf.{}", type_name);
    }

    let lookup_key = format!(".{}", trimmed);
    if let Some(kotlin_full) = type_map.get(&lookup_key) {
        if !current_package.is_empty() {
            let prefix = format!("{}.", current_package);
            if kotlin_full.starts_with(&prefix) {
                return kotlin_full.trim_start_matches(&prefix).to_string();
            }
        }
        return kotlin_full.clone();
    }

    trimmed.rsplit('.').next().unwrap_or(trimmed).to_string()
}

/// Generate Kotlin slimrpc code from a CodeGeneratorRequest
pub fn generate(request: CodeGeneratorRequest) -> Result<CodeGeneratorResponse> {
    let mut response = CodeGeneratorResponse::default();

    let mut file_map: HashMap<String, FileDescriptorProto> = HashMap::new();
    let mut file_info_map: HashMap<String, KotlinFileInfo> = HashMap::new();

    for file in &request.proto_file {
        if let Some(name) = &file.name {
            file_map.insert(name.clone(), file.clone());
            file_info_map.insert(name.clone(), kotlin_file_info(file));
        }
    }

    let mut type_map: HashMap<String, String> = HashMap::new();

    for file in &request.proto_file {
        let Some(file_name) = file.name.as_ref() else {
            continue;
        };
        let info = file_info_map
            .get(file_name.as_str())
            .cloned()
            .unwrap_or_else(|| kotlin_file_info(file));

        let kotlin_prefix = if info.multiple_files {
            info.java_package.clone()
        } else if info.java_package.is_empty() {
            info.outer_class.clone()
        } else {
            format!("{}.{}", info.java_package, info.outer_class)
        };

        let proto_prefix = file.package.clone().unwrap_or_default();
        collect_message_types(
            proto_prefix,
            kotlin_prefix,
            &file.message_type,
            &mut type_map,
        );
    }

    for file_name in &request.file_to_generate {
        let file_descriptor = file_map
            .remove(file_name)
            .context("File descriptor not found")?;

        let info = file_info_map
            .remove(file_name)
            .unwrap_or_else(|| kotlin_file_info(&file_descriptor));

        let kotlin_package = info.java_package;
        let package_decl = if kotlin_package.is_empty() {
            String::new()
        } else {
            format!("package {}", kotlin_package)
        };

        let package_name = file_descriptor.package.clone().unwrap_or_default();

        for service in file_descriptor.service {
            let service_name = service.name.context("Service name missing")?;
            let full_service_name = if package_name.is_empty() {
                service_name.clone()
            } else {
                format!("{}.{}", package_name, service_name)
            };

            let mut client_methods = String::new();
            let mut client_method_impls = String::new();
            let mut server_methods = String::new();
            let mut unimplemented_methods = String::new();
            let mut register_methods = String::new();
            let mut handler_impls = String::new();
            let mut group_client_methods = String::new();
            let mut group_client_method_impls = String::new();

            for method in service.method {
                let method_name = method.name.as_deref().context("Method name missing")?;
                let input_type = method.input_type.as_deref().context("Input type missing")?;
                let output_type = method
                    .output_type
                    .as_deref()
                    .context("Output type missing")?;

                let input_kotlin = resolve_kotlin_type(input_type, &kotlin_package, &type_map);
                let output_kotlin = resolve_kotlin_type(output_type, &kotlin_package, &type_map);

                let t = rpc_templates(
                    method.client_streaming.unwrap_or(false),
                    method.server_streaming.unwrap_or(false),
                );
                let vars = &[
                    ("{{METHOD_NAME}}", method_name),
                    ("{{SERVICE_NAME}}", service_name.as_str()),
                    ("{{INPUT_TYPE}}", input_kotlin.as_str()),
                    ("{{OUTPUT_TYPE}}", output_kotlin.as_str()),
                ];

                client_methods.push_str(&apply(t.client_method, vars));
                client_method_impls.push_str(&apply(t.client_impl, vars));
                server_methods.push_str(&apply(t.server_method, vars));
                unimplemented_methods.push_str(&apply(t.unimplemented, vars));
                register_methods.push_str(&apply(t.register, vars));
                handler_impls.push_str(&apply(t.handler, vars));
                group_client_methods.push_str(&apply(t.group_client_method, vars));
                group_client_method_impls.push_str(&apply(t.group_client_impl, vars));
            }

            let service_content = SERVICE_TEMPLATE
                .replace("{{SERVICE_NAME}}", &service_name)
                .replace("{{FULL_SERVICE_NAME}}", &full_service_name)
                .replace("{{CLIENT_METHODS}}", &client_methods)
                .replace("{{CLIENT_METHOD_IMPLS}}", &client_method_impls)
                .replace("{{SERVER_METHODS}}", &server_methods)
                .replace("{{UNIMPLEMENTED_METHODS}}", &unimplemented_methods)
                .replace("{{REGISTER_METHODS}}", register_methods.trim_end())
                .replace("{{HANDLER_IMPLS}}", &handler_impls)
                .replace("{{GROUP_CLIENT_METHODS}}", &group_client_methods)
                .replace("{{GROUP_CLIENT_METHOD_IMPLS}}", &group_client_method_impls);

            let output_file_name = format!("{}Slimrpc.kt", service_name);
            let output_path = if kotlin_package.is_empty() {
                output_file_name
            } else {
                format!("{}/{}", kotlin_package.replace('.', "/"), output_file_name)
            };

            let final_content = FILE_TEMPLATE
                .replace("{{PROTO_FILE}}", file_name)
                .replace("{{PACKAGE_DECL}}", &package_decl)
                .replace("{{SERVICE_DEFINITION}}", &service_content);

            response.file.push(File {
                name: Some(output_path),
                content: Some(final_content),
                ..Default::default()
            });
        }
    }

    Ok(response)
}

#[cfg(test)]
mod tests {
    use super::*;
    use prost_types::{
        DescriptorProto, FileDescriptorProto, FileOptions, MethodDescriptorProto,
        ServiceDescriptorProto,
    };

    fn create_test_file(
        name: &str,
        package: &str,
        services: Vec<ServiceDescriptorProto>,
        messages: Vec<DescriptorProto>,
    ) -> FileDescriptorProto {
        FileDescriptorProto {
            name: Some(name.to_string()),
            package: Some(package.to_string()),
            service: services,
            message_type: messages,
            ..Default::default()
        }
    }

    fn create_method(
        name: &str,
        input: &str,
        output: &str,
        client_streaming: bool,
        server_streaming: bool,
    ) -> MethodDescriptorProto {
        MethodDescriptorProto {
            name: Some(name.to_string()),
            input_type: Some(input.to_string()),
            output_type: Some(output.to_string()),
            client_streaming: Some(client_streaming),
            server_streaming: Some(server_streaming),
            ..Default::default()
        }
    }

    fn create_service(name: &str, methods: Vec<MethodDescriptorProto>) -> ServiceDescriptorProto {
        ServiceDescriptorProto {
            name: Some(name.to_string()),
            method: methods,
            ..Default::default()
        }
    }

    fn create_message(name: &str) -> DescriptorProto {
        DescriptorProto {
            name: Some(name.to_string()),
            ..Default::default()
        }
    }

    #[test]
    fn test_generate_no_services() {
        let file = create_test_file("test.proto", "test", vec![], vec![]);
        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 0);
    }

    #[test]
    fn test_generate_unary_unary() {
        let method = create_method(
            "GetItem",
            ".test.GetItemRequest",
            ".test.GetItemResponse",
            false,
            false,
        );
        let service = create_service("ItemService", vec![method]);
        let messages = vec![
            create_message("GetItemRequest"),
            create_message("GetItemResponse"),
        ];
        let file = create_test_file("test.proto", "test", vec![service], messages);

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();
        assert!(content.contains("interface ItemServiceClient"));
        assert!(content.contains("interface ItemServiceServer"));
        assert!(content.contains(
            "suspend fun GetItem(request: TestProto.GetItemRequest, timeout: Duration, metadata: Map<String, String>?): TestProto.GetItemResponse"
        ));
        assert!(content.contains(
            "suspend fun GetItem(request: TestProto.GetItemRequest, context: Context): TestProto.GetItemResponse"
        ));
        assert!(content.contains("registerUnaryUnary"));
        assert!(content.contains(": UnaryUnaryHandler"));
    }

    #[test]
    fn test_generate_all_streaming_types() {
        let methods = vec![
            create_method("Unary", ".pkg.Req", ".pkg.Res", false, false),
            create_method("ServerStream", ".pkg.Req", ".pkg.Res", false, true),
            create_method("ClientStream", ".pkg.Req", ".pkg.Res", true, false),
            create_method("BidiStream", ".pkg.Req", ".pkg.Res", true, true),
        ];
        let service = create_service("TestService", methods);
        let messages = vec![create_message("Req"), create_message("Res")];
        let file = create_test_file("test.proto", "pkg", vec![service], messages);

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();
        assert!(content.contains("registerUnaryUnary"));
        assert!(content.contains(": UnaryUnaryHandler"));
        assert!(content.contains("registerUnaryStream"));
        assert!(content.contains(": UnaryStreamHandler"));
        assert!(
            content.contains("suspend fun ServerStream(request: TestProto.Req, timeout: Duration,")
        );
        assert!(content.contains("registerStreamUnary"));
        assert!(content.contains(": StreamUnaryHandler"));
        assert!(content.contains("ClientRequestStream<TestProto.Req, TestProto.Res>"));
        assert!(content.contains("registerStreamStream"));
        assert!(content.contains(": StreamStreamHandler"));
        assert!(content.contains("ClientBidiStream<TestProto.Req>"));
    }

    #[test]
    fn test_generate_multiple_services() {
        let service1 = create_service(
            "ServiceA",
            vec![create_method(
                "MethodA", ".pkg.Req", ".pkg.Res", false, false,
            )],
        );
        let service2 = create_service(
            "ServiceB",
            vec![create_method(
                "MethodB", ".pkg.Req", ".pkg.Res", false, false,
            )],
        );
        let messages = vec![create_message("Req"), create_message("Res")];
        let file = create_test_file("test.proto", "pkg", vec![service1, service2], messages);

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 2);

        let content_a = response.file[0].content.as_ref().unwrap();
        assert!(content_a.contains("object ServiceASlimrpc"));
        assert!(content_a.contains("ServiceAClient"));

        let content_b = response.file[1].content.as_ref().unwrap();
        assert!(content_b.contains("object ServiceBSlimrpc"));
        assert!(content_b.contains("ServiceBClient"));
    }

    #[test]
    fn test_generate_empty_package() {
        let method = create_method("Call", ".Request", ".Response", false, false);
        let service = create_service("MyService", vec![method]);
        let messages = vec![create_message("Request"), create_message("Response")];
        let file = create_test_file("test.proto", "", vec![service], messages);

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();
        assert!(!content.contains("package "));
        assert!(content.contains("SERVICE_NAME = \"MyService\""));
        assert_eq!(
            response.file[0].name.as_ref().unwrap(),
            "MyServiceSlimrpc.kt"
        );
    }

    #[test]
    fn test_generate_google_protobuf_type() {
        let method = create_method(
            "Delete",
            ".test.DeleteRequest",
            ".google.protobuf.Empty",
            false,
            false,
        );
        let service = create_service("TestService", vec![method]);
        let messages = vec![create_message("DeleteRequest")];
        let file = create_test_file("test.proto", "test", vec![service], messages);

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();
        assert!(content.contains("com.google.protobuf.Empty"));
    }

    #[test]
    fn test_generate_nested_message_types() {
        let inner = DescriptorProto {
            name: Some("Inner".to_string()),
            ..Default::default()
        };
        let outer = DescriptorProto {
            name: Some("Outer".to_string()),
            nested_type: vec![inner],
            ..Default::default()
        };
        let method = create_method(
            "DoSomething",
            ".test.Outer.Inner",
            ".test.Outer",
            false,
            false,
        );
        let service = create_service("TestService", vec![method]);
        let file = FileDescriptorProto {
            name: Some("test.proto".to_string()),
            package: Some("test".to_string()),
            service: vec![service],
            message_type: vec![outer],
            ..Default::default()
        };

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();
        assert!(
            content.contains("TestProto.Outer.Inner,"),
            "content was:\n{}",
            content
        );
        assert!(
            content.contains("TestProto.Outer"),
            "content was:\n{}",
            content
        );
    }

    #[test]
    fn test_generate_kotlin_multiple_files() {
        let method = create_method("GetItem", ".test.Request", ".test.Response", false, false);
        let service = create_service("ItemService", vec![method]);
        let messages = vec![create_message("Request"), create_message("Response")];
        let file = FileDescriptorProto {
            name: Some("test.proto".to_string()),
            package: Some("test".to_string()),
            service: vec![service],
            message_type: messages,
            options: Some(FileOptions {
                java_multiple_files: Some(true),
                java_package: Some("com.example.test".to_string()),
                ..Default::default()
            }),
            ..Default::default()
        };

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();
        assert!(
            content.contains("request: Request,"),
            "content was:\n{}",
            content
        );
        assert!(
            content.contains("context: Context): Response"),
            "content was:\n{}",
            content
        );
        let path = response.file[0].name.as_ref().unwrap();
        assert!(path.starts_with("com/example/test/"), "path was: {}", path);
    }

    #[test]
    fn test_generate_group_client() {
        let methods = vec![
            create_method("UnaryUnary", ".pkg.Req", ".pkg.Res", false, false),
            create_method("UnaryStream", ".pkg.Req", ".pkg.Res", false, true),
            create_method("StreamUnary", ".pkg.Req", ".pkg.Res", true, false),
            create_method("StreamStream", ".pkg.Req", ".pkg.Res", true, true),
        ];
        let service = create_service("Test", methods);
        let messages = vec![create_message("Req"), create_message("Res")];
        let file = create_test_file("example.proto", "pkg", vec![service], messages);

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["example.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();

        assert!(content.contains("interface TestGroupClient"));
        assert!(
            content.contains(
                "class TestGroupClientImpl(private val channel: Channel) : TestGroupClient"
            )
        );
        assert!(content.contains("callMulticastUnaryAsync"));
        assert!(content.contains("callMulticastUnaryStreamAsync"));
        assert!(content.contains("callMulticastStreamUnary"));
        assert!(content.contains("callMulticastStreamStream"));
        assert!(content.contains("MulticastResponseStream<"));
        assert!(content.contains("MulticastClientBidiStream<"));
    }

    #[test]
    fn test_generate_kotlin_package_option() {
        let method = create_method("Call", ".test.Request", ".test.Response", false, false);
        let service = create_service("TestService", vec![method]);
        let messages = vec![create_message("Request"), create_message("Response")];
        let file = FileDescriptorProto {
            name: Some("test.proto".to_string()),
            package: Some("test".to_string()),
            service: vec![service],
            message_type: messages,
            options: Some(FileOptions {
                java_package: Some("com.example.myapp".to_string()),
                ..Default::default()
            }),
            ..Default::default()
        };

        let request = CodeGeneratorRequest {
            file_to_generate: vec!["test.proto".to_string()],
            proto_file: vec![file],
            ..Default::default()
        };

        let response = generate(request).unwrap();
        assert_eq!(response.file.len(), 1);

        let content = response.file[0].content.as_ref().unwrap();
        assert!(content.contains("package com.example.myapp"));
        assert!(!content.contains("package com.example.myapp;"));

        let path = response.file[0].name.as_ref().unwrap();
        assert!(path.starts_with("com/example/myapp/"), "path was: {}", path);
        assert!(path.ends_with(".kt"), "path was: {}", path);
    }
}
