// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

/**
 * SlimRPC simple example — server.
 *
 * Implements the `Test` service (all four RPC shapes) generated by
 * protoc-gen-slimrpc-node and serves it over a running SLIM broker.
 *
 * Mirrors python/examples/slimrpc/simple/server.py and
 * go/examples/slimrpc/simple/cmd/server.
 */

import * as slimBindings from '../../../generated/index.js';
import type { ContextLike } from '../../../generated/index.js';
import { createAndConnectApp, splitId, logMessage, DEFAULT_SERVER_ENDPOINT, DEFAULT_SHARED_SECRET } from './common.js';
import { create } from '@bufbuild/protobuf';
import { ExampleResponseSchema, type ExampleRequest, type ExampleResponse } from './types/example_pb.js';
import { registerTestServicer, type TestServicer } from './types/example_slimrpc.js';

const NAME_ORG = 'agntcy';
const NAME_NS = 'grpc';

interface CliArgs {
  instance: string;
  server: string;
}

function parseArgs(): CliArgs {
  const args = process.argv.slice(2);
  let instance = 'server';
  let server = DEFAULT_SERVER_ENDPOINT;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--instance' && i + 1 < args.length) {
      instance = args[++i];
    } else if (args[i] === '--server' && i + 1 < args.length) {
      server = args[++i];
    } else if (args[i] === '--help' || args[i] === '-h') {
      console.log('Usage: npm run server -- [OPTIONS]');
      console.log('');
      console.log('Options:');
      console.log('  --instance <name>   SLIM app name (default: server). Use server1/server2 for group demos.');
      console.log('  --server <address>  SLIM server endpoint (default: http://localhost:46357)');
      console.log('  --help, -h          Show this help message');
      process.exit(0);
    }
  }

  return { instance, server };
}

/**
 * The service implementation. One method per RPC in the proto `Test` service.
 */
class TestService implements TestServicer {
  async ExampleUnaryUnary(request: ExampleRequest, _context: ContextLike): Promise<ExampleResponse> {
    logMessage('server', `📩 unary-unary request: "${request.exampleString}"`);
    return create(ExampleResponseSchema, { exampleString: 'Hello, World!', exampleInteger: 1n });

    // To return a specific gRPC-style error, throw:
    //   throw new slimBindings.RpcError.Rpc({
    //     code: slimBindings.RpcCode.Unimplemented, message: 'not implemented', details: undefined });
    // Any other thrown error is mapped to RpcCode.Internal by the generated handler.
  }

  async *ExampleUnaryStream(request: ExampleRequest, _context: ContextLike): AsyncIterable<ExampleResponse> {
    logMessage('server', `📩 unary-stream request: "${request.exampleString}"`);
    for (let i = 0; i < 5; i++) {
      yield create(ExampleResponseSchema, { exampleString: `Response ${i}`, exampleInteger: BigInt(i) });
    }
  }

  async ExampleStreamUnary(requests: AsyncIterable<ExampleRequest>, _context: ContextLike): Promise<ExampleResponse> {
    logMessage('server', '📩 stream-unary request');
    const seen: string[] = [];
    for await (const request of requests) {
      logMessage('server', `   ↪ got "${request.exampleString}"`);
      seen.push(request.exampleString);
    }
    return create(ExampleResponseSchema, {
      exampleString: `Saw: ${seen.join(', ')}`,
      exampleInteger: BigInt(seen.length),
    });
  }

  async *ExampleStreamStream(requests: AsyncIterable<ExampleRequest>, _context: ContextLike): AsyncIterable<ExampleResponse> {
    logMessage('server', '📩 stream-stream request');
    for await (const request of requests) {
      logMessage('server', `   ↪ echoing "${request.exampleString}"`);
      yield create(ExampleResponseSchema, {
        exampleString: `Echo: ${request.exampleString}`,
        exampleInteger: request.exampleInteger * 100n,
      });
    }
  }
}

async function main(): Promise<void> {
  const args = parseArgs();

  console.log('🚀 SlimRPC Server');
  console.log('=================');
  console.log(`Instance: ${args.instance}`);
  console.log(`Server:   ${args.server}`);
  console.log();

  const localId = `${NAME_ORG}/${NAME_NS}/${args.instance}`;
  const { app, connId } = await createAndConnectApp(localId, args.server, DEFAULT_SHARED_SECRET);

  const localName = splitId(localId);
  const rpcServer = slimBindings.Server.newWithConnection(app, localName, connId);

  registerTestServicer(rpcServer, new TestService());

  console.log('SLIM_RPC_SERVER_READY');
  logMessage(app.id(), `🌐 Server '${args.instance}' is serving. Press Ctrl+C to stop.`);

  await rpcServer.serveAsync();
}

process.on('SIGINT', () => {
  console.log('\n\n📋 Received SIGINT');
  console.log('🛑 Shutting down...');
  process.exit(0);
});

process.on('SIGTERM', () => {
  console.log('\n\n📋 Received SIGTERM');
  console.log('🛑 Shutting down...');
  process.exit(0);
});

main().catch((error: any) => {
  console.error('Fatal error:', error?.message || String(error));
  process.exit(1);
});
