[package]
name = "agntcy-slim-bindings"
version = "2.0.0-alpha.3"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/agntcy/slim-bindings"
description = "UniFFI bindings and FFI adapter for SLIM data plane - enables language integrations (Go, Swift, Kotlin, etc.)"

[lib]
name = "slim_bindings"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
# TODO: switch to version dep once agntcy-slim-bindings is published to crates.io
# slim-bindings-impl = { package = "agntcy-slim-bindings", version = "2.0.0-alpha.2" }
slim-bindings-impl = { package = "agntcy-slim-bindings", git = "https://github.com/agntcy/slim", branch = "feat/remove-slimrpc-from-bindings" }
slim-rpc-impl = { package = "agntcy-slim-rpc", git = "https://github.com/agntcy/slim", branch = "feat/remove-slimrpc-from-bindings", features = ["uniffi"] }
