// Code generated by protoc-gen-slimrpc-kotlin. DO NOT EDIT.
// source: example.proto

package com.example_service

import io.agntcy.slim.bindings.BidiStreamHandler
import io.agntcy.slim.bindings.Channel
import io.agntcy.slim.bindings.Context
import io.agntcy.slim.bindings.RequestStream
import io.agntcy.slim.bindings.RequestStreamWriter
import io.agntcy.slim.bindings.ResponseSink
import io.agntcy.slim.bindings.ResponseStreamReader
import io.agntcy.slim.bindings.RpcCode
import io.agntcy.slim.bindings.RpcException
import io.agntcy.slim.bindings.Server
import io.agntcy.slim.bindings.UnaryStreamHandler
import io.agntcy.slim.bindings.UnaryUnaryHandler
import io.agntcy.slim.bindings.StreamUnaryHandler
import io.agntcy.slim.bindings.StreamStreamHandler
import io.agntcy.slim.bindings.slimrpc.ClientRequestStream
import io.agntcy.slim.bindings.slimrpc.ClientBidiStream
import io.agntcy.slim.bindings.MulticastResponseReader
import io.agntcy.slim.bindings.MulticastBidiStreamHandler
import io.agntcy.slim.bindings.slimrpc.MulticastResponseStream
import io.agntcy.slim.bindings.slimrpc.MulticastClientBidiStream
import io.agntcy.slim.bindings.slimrpc.parse
import io.agntcy.slim.bindings.slimrpc.toRpcException
import java.time.Duration

object TestSlimrpc {
    const val SERVICE_NAME = "example_service.Test"

    interface TestClient {
        suspend fun ExampleUnaryUnary(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): ExampleResponse
        suspend fun ExampleUnaryStream(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): ResponseStreamReader
        fun ExampleStreamUnary(timeout: Duration, metadata: Map<String, String>?): ClientRequestStream<ExampleRequest, ExampleResponse>
        fun ExampleStreamStream(timeout: Duration, metadata: Map<String, String>?): ClientBidiStream<ExampleRequest>

    }

    class TestClientImpl(private val channel: Channel) : TestClient {
        override suspend fun ExampleUnaryUnary(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): ExampleResponse {
            val bytes = channel.callUnaryAsync(
                SERVICE_NAME,
                "ExampleUnaryUnary",
                request.toByteArray(),
                timeout,
                metadata
            )
            return parse(bytes, ExampleResponse.parser())
        }

        override suspend fun ExampleUnaryStream(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): ResponseStreamReader {
            return channel.callUnaryStreamAsync(
                SERVICE_NAME,
                "ExampleUnaryStream",
                request.toByteArray(),
                timeout,
                metadata
            )
        }

        override fun ExampleStreamUnary(timeout: Duration, metadata: Map<String, String>?): ClientRequestStream<ExampleRequest, ExampleResponse> {
            val writer = channel.callStreamUnary(
                SERVICE_NAME,
                "ExampleStreamUnary",
                timeout,
                metadata
            )
            return ClientRequestStream(writer, { it.toByteArray() }, { bytes -> parse(bytes, ExampleResponse.parser()) })
        }

        override fun ExampleStreamStream(timeout: Duration, metadata: Map<String, String>?): ClientBidiStream<ExampleRequest> {
            val handler = channel.callStreamStream(
                SERVICE_NAME,
                "ExampleStreamStream",
                timeout,
                metadata
            )
            return ClientBidiStream(handler) { it.toByteArray() }
        }


    }

    interface TestServer {
        suspend fun ExampleUnaryUnary(request: ExampleRequest, context: Context): ExampleResponse
        suspend fun ExampleUnaryStream(request: ExampleRequest, context: Context, sink: ResponseSink)
        suspend fun ExampleStreamUnary(stream: RequestStream, context: Context): ExampleResponse
        suspend fun ExampleStreamStream(stream: RequestStream, context: Context, sink: ResponseSink)

    }

    open class UnimplementedTestServer : TestServer {
        override suspend fun ExampleUnaryUnary(request: ExampleRequest, context: Context): ExampleResponse {
            throw UnsupportedOperationException("Method ExampleUnaryUnary not implemented")
        }

        override suspend fun ExampleUnaryStream(request: ExampleRequest, context: Context, sink: ResponseSink) {
            throw UnsupportedOperationException("Method ExampleUnaryStream not implemented")
        }

        override suspend fun ExampleStreamUnary(stream: RequestStream, context: Context): ExampleResponse {
            throw UnsupportedOperationException("Method ExampleStreamUnary not implemented")
        }

        override suspend fun ExampleStreamStream(stream: RequestStream, context: Context, sink: ResponseSink) {
            throw UnsupportedOperationException("Method ExampleStreamStream not implemented")
        }


    }

    fun registerTestServer(server: Server, impl: TestServer) {
        server.registerUnaryUnary(SERVICE_NAME, "ExampleUnaryUnary", Test_ExampleUnaryUnary_Handler(impl))
        server.registerUnaryStream(SERVICE_NAME, "ExampleUnaryStream", Test_ExampleUnaryStream_Handler(impl))
        server.registerStreamUnary(SERVICE_NAME, "ExampleStreamUnary", Test_ExampleStreamUnary_Handler(impl))
        server.registerStreamStream(SERVICE_NAME, "ExampleStreamStream", Test_ExampleStreamStream_Handler(impl))
    }

    private class Test_ExampleUnaryUnary_Handler(private val impl: TestServer) : UnaryUnaryHandler {
        override suspend fun handle(request: ByteArray, context: Context): ByteArray {
            val parsed = parse(request, ExampleRequest.parser())
            return impl.ExampleUnaryUnary(parsed, context).toByteArray()
        }
    }

    private class Test_ExampleUnaryStream_Handler(private val impl: TestServer) : UnaryStreamHandler {
        override suspend fun handle(request: ByteArray, context: Context, sink: ResponseSink) {
            val parsed = try {
                parse(request, ExampleRequest.parser())
            } catch (e: Exception) {
                val rpcErr = RpcException.Rpc(RpcCode.INVALID_ARGUMENT, e.message ?: "invalid request", null)
                try { sink.sendErrorAsync(rpcErr) } catch (_: Exception) {}
                throw rpcErr
            }
            try {
                impl.ExampleUnaryStream(parsed, context, sink)
                sink.closeAsync()
            } catch (e: Exception) {
                val rpcErr = toRpcException(e, RpcCode.INTERNAL)
                try { sink.sendErrorAsync(rpcErr) } catch (_: Exception) {}
                throw rpcErr
            }
        }
    }

    private class Test_ExampleStreamUnary_Handler(private val impl: TestServer) : StreamUnaryHandler {
        override suspend fun handle(stream: RequestStream, context: Context): ByteArray {
            try {
                return impl.ExampleStreamUnary(stream, context).toByteArray()
            } catch (e: Exception) {
                throw toRpcException(e, RpcCode.INTERNAL)
            }
        }
    }

    private class Test_ExampleStreamStream_Handler(private val impl: TestServer) : StreamStreamHandler {
        override suspend fun handle(stream: RequestStream, context: Context, sink: ResponseSink) {
            try {
                impl.ExampleStreamStream(stream, context, sink)
                sink.closeAsync()
            } catch (e: Exception) {
                val rpcErr = toRpcException(e, RpcCode.INTERNAL)
                try { sink.sendErrorAsync(rpcErr) } catch (_: Exception) {}
                throw rpcErr
            }
        }
    }


    interface TestGroupClient {
        suspend fun ExampleUnaryUnary(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<ExampleResponse>
        suspend fun ExampleUnaryStream(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<ExampleResponse>
        fun ExampleStreamUnary(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<ExampleRequest, ExampleResponse>
        fun ExampleStreamStream(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<ExampleRequest, ExampleResponse>

    }

    class TestGroupClientImpl(private val channel: Channel) : TestGroupClient {
        override suspend fun ExampleUnaryUnary(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<ExampleResponse> {
            val reader = channel.callMulticastUnaryAsync(
                SERVICE_NAME,
                "ExampleUnaryUnary",
                request.toByteArray(),
                timeout,
                metadata
            )
            return MulticastResponseStream(reader) { bytes -> parse(bytes, ExampleResponse.parser()) }
        }

        override suspend fun ExampleUnaryStream(request: ExampleRequest, timeout: Duration, metadata: Map<String, String>?): MulticastResponseStream<ExampleResponse> {
            val reader = channel.callMulticastUnaryStreamAsync(
                SERVICE_NAME,
                "ExampleUnaryStream",
                request.toByteArray(),
                timeout,
                metadata
            )
            return MulticastResponseStream(reader) { bytes -> parse(bytes, ExampleResponse.parser()) }
        }

        override fun ExampleStreamUnary(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<ExampleRequest, ExampleResponse> {
            val handler = channel.callMulticastStreamUnary(
                SERVICE_NAME,
                "ExampleStreamUnary",
                timeout,
                metadata
            )
            return MulticastClientBidiStream(handler, { it.toByteArray() }, { bytes -> parse(bytes, ExampleResponse.parser()) })
        }

        override fun ExampleStreamStream(timeout: Duration, metadata: Map<String, String>?): MulticastClientBidiStream<ExampleRequest, ExampleResponse> {
            val handler = channel.callMulticastStreamStream(
                SERVICE_NAME,
                "ExampleStreamStream",
                timeout,
                metadata
            )
            return MulticastClientBidiStream(handler, { it.toByteArray() }, { bytes -> parse(bytes, ExampleResponse.parser()) })
        }


    }
}

