# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-test-and-build-bindings

on:
  push:
    paths:
      - '.github/workflows/pr.yaml'
      - '.github/workflows/reusable-bindings-build-and-test.yaml'
      - '.github/workflows/reusable-dotnet-build-and-test.yaml'
      - '.github/workflows/reusable-java-build-and-test.yaml'
      - '.github/workflows/reusable-kotlin-build-and-test.yaml'
      - '.github/actions/setup-rust/action.yaml'
      - 'rust/**'
      - 'python/**'
      - 'go/**'
      - 'dotnet/**'
      - 'java/**'
      - 'kotlin/**'
      - 'node/**'
      - 'react-native/**'
      - 'slimrpc-compiler/**'
      - 'tasks/**'
      - 'Taskfile.yaml'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/pr.yaml'
      - '.github/workflows/reusable-bindings-build-and-test.yaml'
      - '.github/workflows/reusable-dotnet-build-and-test.yaml'
      - '.github/workflows/reusable-java-build-and-test.yaml'
      - '.github/workflows/reusable-kotlin-build-and-test.yaml'
      - '.github/actions/setup-rust/action.yaml'
      - 'rust/**'
      - 'python/**'
      - 'go/**'
      - 'dotnet/**'
      - 'java/**'
      - 'kotlin/**'
      - 'node/**'
      - 'react-native/**'
      - 'slimrpc-compiler/**'
      - 'tasks/**'
      - 'Taskfile.yaml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  bindings-build-and-test:
    name: Bindings - build & test
    uses: ./.github/workflows/reusable-bindings-build-and-test.yaml

  slimrpc-compiler-build-and-test:
    name: slimrpc-compiler - build & test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          workspace: ./slimrpc-compiler

      - name: Build
        working-directory: ./slimrpc-compiler
        run: cargo build --locked --all-targets

      - name: Test
        working-directory: ./slimrpc-compiler
        run: cargo test --locked --all-targets

      - name: Clippy
        working-directory: ./slimrpc-compiler
        run: cargo clippy --locked --all-targets -- -D warnings

      - name: Format
        working-directory: ./slimrpc-compiler
        run: cargo fmt --all -- --check
